version: "2"

linters:
  default: none
  enable:
    - loglintergo

  settings:
    custom:
      loglintergo:
        type: module
        description: "Custom log linter"
        settings:
          strict: true
          rules:
            lowercase: true
            english: true
            emoji_or_special: true
            sensitive: true
          sensitive_patterns:
              - '(?i)\b(token|secret|api[_-]?key)\b\s*[:=]'
              - '(?i)\bauthorization\b\s*:\s*bearer\b'
